[package]
name = "monero-generators"
version = "0.4.0"
description = "Monero's hash_to_point and generators"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/coins/monero/generators"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
std-shims = { path = "../../../common/std-shims", version = "^0.1.1", default-features = false }

subtle = { version = "^2.4", default-features = false }

sha3 = { version = "0.10", default-features = false }

curve25519-dalek = { version = "4", default-features = false, features = ["alloc", "zeroize", "precomputed-tables"] }

group = { version = "0.13", default-features = false }
dalek-ff-group = { path = "../../../crypto/dalek-ff-group", version = "0.4" }

[features]
std = ["std-shims/std"]
default = ["std"]
