[package]
name = "flexible-transcript"
version = "0.1.3"
description = "A simple transcript trait definition, along with viable options"
license = "MIT"
repository = "https://github.com/serai-dex/serai"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = ["transcript"]
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
digest = "0.10"

blake2 = { version = "0.10", optional = true }
merlin = { version = "3", optional = true }

[features]
recommended = ["blake2"]
merlin = ["dep:merlin"]
