[package]
name = "multiexp"
version = "0.2.1"
description = "Multiexponentation algorithms for ff/group"
license = "MIT"
repository = "https://github.com/serai-dex/serai"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = ["multiexp", "ff", "group"]
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
zeroize = { version = "1.5", features = ["zeroize_derive"] }

ff = "0.12"
group = "0.12"

rand_core = { version = "0.6", optional = true }

[dev-dependencies]
rand_core = "0.6"

k256 = { version = "0.11", features = ["bits"] }
dalek-ff-group = { path = "../dalek-ff-group" }

[features]
batch = ["rand_core"]
