[package]
name = "tokens-pallet"
version = "0.1.0"
description = "Mint and burn Serai tokens"
license = "AGPL-3.0-only"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
edition = "2021"
publish = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive", "max-encoded-len"] }
scale-info = { version = "2", default-features = false, features = ["derive"] }

frame-system = { git = "https://github.com/serai-dex/substrate", default-features = false }
frame-support = { git = "https://github.com/serai-dex/substrate", default-features = false }

pallet-assets = { git = "https://github.com/serai-dex/substrate", default-features = false }

serai-primitives = { path = "../..//primitives", default-features = false }
tokens-primitives = { path = "../primitives", default-features = false }

[features]
std = [
  "scale/std",
  "scale-info/std",

  "frame-system/std",
  "frame-support/std",

  "pallet-assets/std",

  "serai-primitives/std",
]
default = ["std"]
