[package]
name = "ff-group-tests"
version = "0.13.0"
description = "A collection of sanity tests for implementors of ff/group APIs"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/crypto/ff-group-tests"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = ["ff", "group", "ecc"]
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
rand_core = "0.6"

subtle = "^2.4"

group = "0.13"

[dev-dependencies]
k256 = { version = "^0.13.1", features = ["bits"] }
p256 = { version = "^0.13.1", features = ["bits"] }

bls12_381 = "0.8"

pasta_curves = "0.5"
