[package]
name = "ff-group-tests"
version = "0.12.0"
description = "A collection of sanity tests for implementors of ff/group APIs"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/crypto/ff-group-tests"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = ["ff", "group", "ecc"]
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
rand_core = "0.6"
group = "0.12"

[dev-dependencies]
k256 = { version = "0.12", features = ["bits"] }
p256 = { version = "0.12", features = ["bits"] }
