name: coins/ Tests

on:
  push:
    branches:
      - develop
    paths:
      - "common/**"
      - "crypto/**"
      - "coins/**"

  pull_request:
    paths:
      - "common/**"
      - "crypto/**"
      - "coins/**"

  workflow_dispatch:

jobs:
  test-coins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: Test Dependencies
        uses: ./.github/actions/test-dependencies
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests
        run: |
          GITHUB_CI=true RUST_BACKTRACE=1 cargo nextest run --all-features \
            -p bitcoin-serai \
            -p ethereum-serai \
            -p monero-generators \
            -p monero-serai
