[package]
name = "frost-schnorrkel"
version = "0.1.0"
description = "modular-frost Algorithm compatible with Schnorrkel"
license = "MIT"
repository = "https://github.com/serai-dex/serai/tree/develop/crypto/schnorrkel"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = ["frost", "multisig", "threshold", "schnorrkel"]
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
rand_core = "0.6"
zeroize = "^1.5"

transcript = { package = "flexible-transcript", path = "../transcript", version = "0.3", features = ["merlin"] }

group = "0.13"

ciphersuite = { path = "../ciphersuite", version = "0.3", features = ["std", "ristretto"] }
schnorr = { package = "schnorr-signatures", path = "../schnorr", version = "0.4" }
frost = { path = "../frost", package = "modular-frost", version = "0.7", features = ["ristretto"] }

schnorrkel = { version = "0.11", git = "https://github.com/serai-dex/schnorrkel" }

[dev-dependencies]
frost = { path = "../frost", package = "modular-frost", features = ["tests"] }
